// actionTypes.js
export const CREATE_CASH_REQUEST = "CREATE_CASH_REQUEST";
export const CREATE_CASH_REQUEST_SUCCESS = "CREATE_CASH_REQUEST_SUCCESS";
export const CREATE_CASH_REQUEST_FAILURE = "CREATE_CASH_REQUEST_FAILURE";
