export const FETCH_MENU_MANAGEMENT_REQUEST = "FETCH_MENU_MANAGEMENT_REQUEST";
export const FETCH_MENU_MANAGEMENT_SUCCESS = "FETCH_MENU_MANAGEMENT_SUCCESS";
export const FETCH_MENU_MANAGEMENT_FAILURE = "FETCH_MENU_MANAGEMENT_FAILURE";

export const ADD_MENU_SLOT_REQUEST = "ADD_MENU_SLOT_REQUEST";
export const ADD_MENU_SLOT_SUCCESS = "ADD_MENU_SLOT_SUCCESS";
export const ADD_MENU_SLOT_FAILURE = "ADD_MENU_SLOT_FAILURE";

export const REMOVE_MENU_SLOT_REQUEST = "REMOVE_MENU_SLOT_REQUEST";
export const REMOVE_MENU_SLOT_SUCCESS = "REMOVE_MENU_SLOT_SUCCESS";
export const REMOVE_MENU_SLOT_FAILURE = "REMOVE_MENU_SLOT_FAILURE";
